export const colors = [
  "bg-clr-default",
  "bg-clr-red",
  "bg-clr-orange",
  "bg-clr-yellow",
  "bg-clr-lime",
  "bg-clr-emerald",
  "bg-clr-cyan",
  "bg-clr-blue",
  "bg-clr-indigo",
  "bg-clr-violet",
  "bg-clr-fuchsia",
  "bg-clr-rose",
  "bg-clr-stone",
];
